In [46]:
import numpy as np

# Matrix Creation

In [47]:


# From a list
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# From a tuple
matrix2 = np.array(((1, 2, 3),
                    (4, 5, 6),
                    (7, 8, 9)))



print (f'matrix from a list: {matrix1}')

print (f'matrix from a tuple: {matrix2}')



matrix from a list: [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix from a tuple: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
# Using the np.matrix function

matrix3 = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12')

print (f'matrix using matrix function: {matrix3}')

matrix using matrix function: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
# 3x3 matrix filled with zeros
zeros_matrix = np.zeros((3, 3))

# 3x3 matrix filled with ones
ones_matrix = np.ones((3, 3))

# 3x3 matrix filled with a specific value (e.g., 5)
constant_matrix = np.full((3, 3), 5)


print (f'matrix filled with zeros: {zeros_matrix}')

print (f'matrix filled with ones: {ones_matrix}')

print (f'matrix filled with a specific value: {constant_matrix}')

matrix filled with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
matrix filled with ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
matrix filled with a specific value: [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [50]:
# 3x3 identity matrix
identity_matrix = np.eye(3)

# Diagonal matrix from a list of diagonal elements
diagonal_matrix = np.diag([1, 2, 3])

print (f'Identity matrix: {identity_matrix}')

print (f'diagonal matrix: {diagonal_matrix}')


Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diagonal matrix: [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [51]:
# 3x3 matrix with random numbers from a uniform distribution in [0, 1)
random_matrix_uniform = np.random.rand(3, 3)

# 3x3 matrix with random numbers from a standard normal distribution (mean=0, std=1)
random_matrix_normal = np.random.randn(3, 3)

print (f'Uniform random matrix: {random_matrix_uniform}')

print (f'Uniform normal matrix: {random_matrix_normal}')


Uniform random matrix: [[0.55192442 0.47554075 0.16964158]
 [0.65812634 0.84297482 0.61921691]
 [0.67319584 0.34134358 0.84129038]]
Uniform normal matrix: [[ 0.90221014  1.60608033  0.97151039]
 [ 1.48515955  0.49263218  0.11675949]
 [-0.86083955 -0.54079195  0.09520094]]


In [52]:
# Create a 1D array and reshape it into a 3x3 matrix
matrix_from_1d_array = np.arange(1, 10).reshape(3, 3)

print (f'Matrix from 1D array: {matrix_from_1d_array}')

Matrix from 1D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Matrix  Operations

In [53]:

matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])


# matrix addition
result_matrix = matrix1 + matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of matrix addition:")
print(result_matrix)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [54]:
# matrix subtraction



matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])


result_matrix = matrix1 - matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of matrix subtraction:")
print(result_matrix)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [55]:
# Scalar Multiplication


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Define a scalar
scalar = 2

# Perform scalar multiplication
result_matrix = scalar * matrix

print("Original Matrix:")
print(matrix)

print("\nScalar:")
print(scalar)

print("\nResult of scalar multiplication:")
print(result_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Scalar:
2

Result of scalar multiplication:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [56]:
# Matrix Multiplication



matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])


# Method 1: Using np.dot()
result_matrix1 = np.dot(matrix1, matrix2)

# Method 2: Using @ operator
result_matrix2 = matrix1 @ matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of matrix multiplication (using np.dot()):")
print(result_matrix1)

print("\nResult of matrix multiplication (using @ operator):")
print(result_matrix2)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix multiplication (using np.dot()):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Result of matrix multiplication (using @ operator):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [57]:
# Hadamard product or Element wise Product



matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Perform Hadamard product
result_matrix = matrix1 * matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Hadamard product:")
print(result_matrix)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of Hadamard product:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [58]:
# Determinant of a Matrix


matrix = np.array([[1, 2],
                   [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Matrix:")
print(matrix)

print("\nDeterminant:", determinant)

Matrix:
[[1 2]
 [3 4]]

Determinant: -2.0000000000000004


In [59]:
#Trace of a matrix


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace = np.trace(matrix)

print("Matrix:")
print(matrix)

print("\nTrace:", trace)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace: 15


In [60]:
#Transpose of a Matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

transpose_matrix = matrix.T  # Using .T attribute
# Alternatively: transpose_matrix = np.transpose(matrix)

print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [61]:
#Rank of a Matrix



matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)

print("\nRank:", rank)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


In [62]:
#Inverse of a Matrix


matrix = np.array([[1, 2],
                   [3, 4]])

inverse_matrix = np.linalg.inv(matrix)

print("Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [63]:
#Moore Penrose Inverse of a Matrix


matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

pseudoinverse_matrix = np.linalg.pinv(matrix)

print("Matrix:")
print(matrix)

print("\nMoore-Penrose Pseudoinverse:")
print(pseudoinverse_matrix)

Matrix:
[[1 2]
 [3 4]
 [5 6]]

Moore-Penrose Pseudoinverse:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [64]:
# Matrix Vstack


matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Vertical stacking
vertical_stack = np.vstack((matrix1, matrix2))

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nVertical Stack:")
print(vertical_stack)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Vertical Stack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
# Matrix Hstack


matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Vertical stacking
horizontal_stack = np.hstack((matrix1, matrix2))

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nHorizontal Stack:")
print(horizontal_stack)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Horizontal Stack:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [66]:
# Matrix Dstack


matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Depth-wise stacking
depth_stack = np.dstack((matrix1, matrix2))

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nDepth-wise Stack:")
print(depth_stack)

Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8  9]
 [10 11 12]]

Depth-wise Stack:
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [67]:
# Hermitian Transpose



# Define a complex matrix
matrix = np.array([[1 + 2j, 3 - 4j],
                   [5 + 6j, 7 - 8j]])

conjugate_transpose_matrix = matrix.conj().T

print("Matrix:")
print(matrix)

print("\nConjugate Transpose Matrix:")
print(conjugate_transpose_matrix)

Matrix:
[[1.+2.j 3.-4.j]
 [5.+6.j 7.-8.j]]

Conjugate Transpose Matrix:
[[1.-2.j 5.-6.j]
 [3.+4.j 7.+8.j]]
