# Tensor Properties

## Rank

In [1]:
import torch

# Create a 3D tensor (rank 3)
tensor = torch.ones(2, 3, 4)

# Find the rank (number of dimensions)
rank1 = tensor.dim()
rank2 = tensor.ndim
print(f"Rank of the tensor: {rank1}")
print(f"Rank of the tensor: {rank2}")

Rank of the tensor: 3
Rank of the tensor: 3


##Shape

In [2]:
# Create a 2D tensor
tensor = torch.randn(5, 3)

# Get the shape of the tensor
shape = tensor.shape
size  = tensor.size()

print(f"Shape of the tensor: {shape}")

print(f"Shape of the tensor: {size}")

Shape of the tensor: torch.Size([5, 3])
Shape of the tensor: torch.Size([5, 3])


## Data Type

In [3]:
# Create a float tensor
tensor = torch.tensor([1.0, 2.0, 3.0])

# Find the data type of the tensor
data_type = tensor.dtype
print(f"Data type of the tensor: {data_type}")

Data type of the tensor: torch.float32


In [4]:
# Float 32 tensor

float_32_tensor = torch.tensor([2.0,4.0,8.0],
                               dtype = None,
                               device=None,
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [5]:
#changing tensor datatypes

float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([2., 4., 8.], dtype=torch.float16)

##Device Type

In [6]:
# Create a tensor and move it to GPU if available
tensor = torch.randn(3, 3).to('cuda' if torch.cuda.is_available() else 'cpu')

# Check the device type
device = tensor.device
print(f"Tensor is on device: {device}")

Tensor is on device: cpu


##Gradient Tracking

In [7]:
# Create a tensor with gradient tracking
tensor = torch.randn(2, 2, requires_grad=True)

# Check if the tensor is tracking gradients
is_tracking_grad = tensor.requires_grad
print(f"Is tensor tracking gradients? {is_tracking_grad}")

Is tensor tracking gradients? True


# Tensor Types

In [8]:
# Zero-order tensor (scalar)
zero_order_tensor = torch.tensor(42)
print("Zero-Order Tensor:", zero_order_tensor)
print("Shape:", zero_order_tensor.shape)  # Output: torch.Size([])
print("Rank (ndim):", zero_order_tensor.ndim)  # Output: 0

Zero-Order Tensor: tensor(42)
Shape: torch.Size([])
Rank (ndim): 0


In [9]:
# First-order tensor (vector)
first_order_tensor = torch.tensor([1, 2, 3, 4])
print("\nFirst-Order Tensor:", first_order_tensor)
print("Shape:", first_order_tensor.shape)  # Output: torch.Size([4])
print("Rank (ndim):", first_order_tensor.ndim)  # Output: 1


First-Order Tensor: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Rank (ndim): 1


In [10]:
# Second-order tensor (matrix)
second_order_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("\nSecond-Order Tensor:", second_order_tensor)
print("Shape:", second_order_tensor.shape)  # Output: torch.Size([3, 2])
print("Rank (ndim):", second_order_tensor.ndim)  # Output: 2


Second-Order Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])
Rank (ndim): 2


In [11]:
# Third-order tensor (3D tensor)
third_order_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nThird-Order Tensor:", third_order_tensor)
print("Shape:", third_order_tensor.shape)  # Output: torch.Size([2, 2, 2])
print("Rank (ndim):", third_order_tensor.ndim)  # Output: 3


Third-Order Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Rank (ndim): 3


In [12]:
# Fourth-order tensor (4D tensor)

fourth_order_tensor = torch.randn(2, 3, 4, 5)  # Random tensor with 4 dimensions
print("\nFourth-Order Tensor:", fourth_order_tensor)
print("Shape:", fourth_order_tensor.shape)  # Output: torch.Size([2, 3, 4, 5])
print("Rank (ndim):", fourth_order_tensor.ndim)  # Output: 4


Fourth-Order Tensor: tensor([[[[ 0.7184, -1.1759,  0.3779,  1.2230,  0.4053],
          [ 0.5445, -0.1487,  1.7159,  0.1013, -0.3567],
          [ 1.7053,  0.1474,  0.4381,  0.7176,  1.0513],
          [ 0.7621, -0.2378, -2.2279, -1.6423,  1.1999]],

         [[ 1.5113,  2.3815,  0.6530, -0.7108, -0.3061],
          [-0.9021,  0.4295,  1.2186,  0.3343, -1.1468],
          [-0.5641, -0.7349,  0.0927, -0.3744, -1.1019],
          [ 0.7269, -0.8991, -1.4320, -0.0114,  0.1915]],

         [[-0.8226,  0.9726, -1.6931, -0.0718, -1.4218],
          [ 0.1519,  0.2318, -1.8445,  2.7314, -2.1557],
          [-0.7162,  0.1386,  0.2182,  1.8131, -1.4794],
          [-1.2180, -0.3261, -0.2293, -0.3521,  0.0360]]],


        [[[ 0.5601, -0.5021,  1.4304,  0.5707,  0.6636],
          [ 0.4410,  0.1389,  1.1070,  1.9952, -0.4964],
          [-0.2074, -0.6577, -0.2493, -0.8475,  1.3141],
          [-0.3977, -0.1704,  0.8616,  1.0934,  0.0063]],

         [[ 1.4011, -1.1522, -0.0458,  0.6235, -0.6250],

# Tensor Creation

In [13]:
# Random tensor of shape (3, 3) with values sampled from a uniform distribution
random_tensor = torch.rand(3, 3)
print("Random Tensor (Uniform Distribution):\n", random_tensor)

# Random tensor of shape (3, 3) with values sampled from a normal (Gaussian) distribution
random_normal_tensor = torch.randn(3, 3)
print("\nRandom Tensor (Normal Distribution):\n", random_normal_tensor)

Random Tensor (Uniform Distribution):
 tensor([[0.5563, 0.8899, 0.2254],
        [0.2598, 0.0212, 0.0812],
        [0.8356, 0.4148, 0.3470]])

Random Tensor (Normal Distribution):
 tensor([[-1.7291, -1.0753, -1.4712],
        [ 0.1021, -0.4217, -0.5622],
        [ 0.9506, -0.1003, -0.0793]])


In [14]:
# Tensor of all zeros of shape (2, 2)
zero_tensor = torch.zeros(2, 2)
print("Zeros Tensor:\n", zero_tensor)

# Tensor of all ones of shape (2, 2)
ones_tensor = torch.ones(2, 2)
print("\nOnes Tensor:\n", ones_tensor)

Zeros Tensor:
 tensor([[0., 0.],
        [0., 0.]])

Ones Tensor:
 tensor([[1., 1.],
        [1., 1.]])


In [15]:
# Tensor with values from 0 to 9
range_tensor = torch.arange(10)
print("Range Tensor:\n", range_tensor)

# Tensor with values from 0 to 9, with step size of 2
step_range_tensor = torch.arange(0, 10, 2)
print("\nRange Tensor with step size 2:\n", step_range_tensor)

Range Tensor:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Range Tensor with step size 2:
 tensor([0, 2, 4, 6, 8])


In [16]:
# Create a random tensor
original_tensor = torch.randn(3, 3)

# Create a new tensor with the same shape and properties as `original_tensor`, but filled with zeros
zeros_like_tensor = torch.zeros_like(original_tensor)
print("Zeros-Like Tensor:\n", zeros_like_tensor)

# Create a new tensor with the same shape and properties as `original_tensor`, but filled with ones
ones_like_tensor = torch.ones_like(original_tensor)
print("\nOnes-Like Tensor:\n", ones_like_tensor)

Zeros-Like Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones-Like Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
# Tensor with all elements set to a constant value of 5
constant_tensor = torch.full((3, 3), 5)
print("\nConstant Tensor:\n", constant_tensor)


Constant Tensor:
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [18]:
# 3x3 identity matrix
identity_tensor = torch.eye(3)
print("\nIdentity Tensor:\n", identity_tensor)


Identity Tensor:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [19]:
# Tensor with 5 equally spaced values between 0 and 10
linspace_tensor = torch.linspace(0, 10, steps=5)
print("\nLinspace Tensor:\n", linspace_tensor)


Linspace Tensor:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [20]:
# Empty tensor of shape (2, 2)

empty_tensor = torch.empty(2, 2)
print("\nEmpty Tensor:\n", empty_tensor)


Empty Tensor:
 tensor([[1.9472e-07, 3.3365e-41],
        [6.8799e-04, 4.3269e-41]])


In [21]:
# Tensor from a Python list
list_tensor = torch.tensor([1, 2, 3, 4])
print("\nTensor from List:\n", list_tensor)

# Tensor from a NumPy array
import numpy as np
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print("\nTensor from NumPy array:\n", tensor_from_numpy)


Tensor from List:
 tensor([1, 2, 3, 4])

Tensor from NumPy array:
 tensor([1, 2, 3])


# Tensor Operations


## Arithmetic Operations

In [22]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Element-wise addition
result_add = torch.add(tensor_a, tensor_b)
print(result_add)

tensor([[ 6,  8],
        [10, 12]])


In [23]:
#Subtraction

result_sub = torch.subtract(tensor_a, tensor_b)
print(result_sub)

tensor([[-4, -4],
        [-4, -4]])


In [24]:
#Multiplication

result_mul = torch.multiply(tensor_a, tensor_b)
print(result_mul)

tensor([[ 5, 12],
        [21, 32]])


In [25]:
# Division

result_div = torch.divide(tensor_a, tensor_b)
print(result_div)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


## Matrix Operations

In [26]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
result_matmul = torch.matmul(tensor_a, tensor_b)
print(result_matmul)

tensor([[19, 22],
        [43, 50]])


In [27]:
# Transposing a tensor
result_transpose = tensor_a.t()
print(result_transpose)

tensor([[1, 3],
        [2, 4]])


## Reduction Operations

In [28]:
#sum

result_sum = torch.sum(tensor_a)
print(result_sum)

tensor(10)


In [29]:
#mean

result_mean = torch.mean(tensor_a.float())
print(result_mean)

tensor(2.5000)


In [30]:
#max

result_max = torch.max(tensor_a)
print(result_max)

tensor(4)


## Indexing and Slicing

In [31]:
# Access element at row 0, column 1

element = tensor_a[0, 1]
print(element)

tensor(2)


In [32]:
# Slicing: Select all rows, second column

slice_tensor = tensor_a[:, 1]
print(slice_tensor)

tensor([2, 4])


## Reshaping

In [33]:
# Changing the shape of a tensor (2x2 to 4x1)

reshaped_tensor = tensor_a.view(4, 1)
print(reshaped_tensor)

tensor([[1],
        [2],
        [3],
        [4]])


## Broadcasting

In [34]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([[1], [2], [3]])

# Broadcasting allows element-wise addition of different shapes
result_broadcast = tensor_a + tensor_b
print(result_broadcast)

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


## Other Common Operations

In [35]:
# Create a tensor with values from 0 to 9
arange_tensor = torch.arange(10)
print(arange_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
# Create a tensor with random permutation of integers from 0 to 9
randperm_tensor = torch.randperm(10)
print(randperm_tensor)

tensor([5, 1, 4, 6, 7, 2, 0, 8, 3, 9])


In [37]:
# Create a tensor with uniform random values between 0 and 1
uniform_tensor = torch.empty(3, 3).uniform_(0, 1)
print(uniform_tensor)

tensor([[0.0463, 0.5272, 0.4778],
        [0.8243, 0.9959, 0.3424],
        [0.3541, 0.3129, 0.4393]])
