In [12]:
import numpy as np

# Vector Creation

In [13]:
horizontal_list = [1, 2, 3]

vertical_list = [[10],[20],[30]]

Array = np.array([1,2,3]) # 1D array

row_vector = np.array([ [1,2,3] ]) # row
column_vector = np.array([ [1],[2],[3] ]) #column

row_vector_from_list = np.array(horizontal_list)
column_vector_from_list = np.array(vertical_list)

print (f'horizontal list: {horizontal_list}')
print (f'vertical list: {vertical_list}')
print (f'array: {Array}')
print (f'row vector: {row_vector}')
print (f'column vector: {column_vector}')
print (f'row vector from list: {row_vector_from_list}')
print (f'column vector from list:{column_vector_from_list}')

horizontal list: [1, 2, 3]
vertical list: [[10], [20], [30]]
array: [1 2 3]
row vector: [[1 2 3]]
column vector: [[1]
 [2]
 [3]]
row vector from list: [1 2 3]
column vector from list:[[10]
 [20]
 [30]]


# Magnitude/Norm of a vector

In [14]:
# L-0 Norm

v = np.array([1, 0, 3, 0, 5]) #sample vector

l0_norm = np.linalg.norm(v, ord=0)

print("L0-norm of vector v:", l0_norm)

L0-norm of vector v: 3.0


In [15]:
# L-1 Norm

v = np.array([1, -2, 3, -4, 5]) #sample vector

l1_norm = np.linalg.norm(v, ord=1)

print("L1-norm of vector v:", l1_norm)

L1-norm of vector v: 15.0


In [16]:
# L-2 Norm

v = np.array([1, 2, 3, 4, 5]) #sample vector

l2_norm = np.linalg.norm(v, ord=2)

print("L2-norm of vector v:", l2_norm)

L2-norm of vector v: 7.416198487095663


In [17]:
# L-2 Norm

v = np.array([1, 2, 3, 4, 5]) #sample vector

l2_norm = np.linalg.norm(v)

print("L2-norm of vector v:", l2_norm)

L2-norm of vector v: 7.416198487095663


In [18]:
# L-infinity Norm

v = np.array([-8 ,6 , 2, 3, 7]) #sample vector

linfinity_norm = np.linalg.norm(v, ord=np.inf)

print("L-infinity norm of vector v:", linfinity_norm)

L-infinity norm of vector v: 8.0


# Angle

In [19]:
#Direction Angle of a Vector


v = np.array([3, 4])

angle_rad = np.arctan2(v[1], v[0])  # arctan2(y, x) gives the angle in radians

# Convert the angle to degrees
angle_deg = np.degrees(angle_rad)

print("Angle of vector v in degrees:", angle_deg)

Angle of vector v in degrees: 53.13010235415598


In [20]:
#Angle between Two Vectors

u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Compute the dot product of the two vectors
dot_product = np.dot(u, v)

# Compute the norms of the vectors
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

# Calculate the cosine of the angle between the vectors using the dot product and norms
cosine_angle = dot_product / (norm_u * norm_v)

# Calculates the angle in radians
angle_rad = np.arccos(cosine_angle)

# Convert the angle to degrees
angle_deg = np.degrees(angle_rad)

print("Angle between vectors u and v in degrees:", angle_deg)

Angle between vectors u and v in degrees: 35.02287072387793


# Vector Operations

In [21]:
#Vector addition
u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Add vectors
result = u + v

print("Result of adding vectors u and v:", result)

Result of adding vectors u and v: [0 3 7]


In [22]:
#Vector Subtraction

u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Subtract the second vector from the first vector
result = u - v

print("Result of subtracting vector v from vector u:", result)

Result of subtracting vector v from vector u: [ 2  1 -1]


In [23]:
#Broadcasting

u = np.array([[1, 2, 3]])
v = np.array([[-1], [1], [4]])

# Ensure that the shapes are compatible for broadcasting

result = u + v

print("Result of broadcasting vectors u and v:", result)

Result of broadcasting vectors u and v: [[0 1 2]
 [2 3 4]
 [5 6 7]]


In [24]:
#Broadcasting

u = np.array([[1, 2, 3]])
v = np.array([[-1], [1], [4]])

# Ensure that the shapes are compatible for broadcasting

result = u * v

print("Result of broadcasting vectors u and v:", result)

Result of broadcasting vectors u and v: [[-1 -2 -3]
 [ 1  2  3]
 [ 4  8 12]]


In [25]:
# Dot Product using np.dot

u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Compute the dot product of u and v
dot_product = np.dot(u, v)

print("Dot product of vectors u and v:", dot_product)

Dot product of vectors u and v: 13


In [26]:
# Dot Product using @


u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Compute the dot product of u and v using the @ operator
dot_product = u @ v

print("Dot product of vectors u and v:", dot_product)

Dot product of vectors u and v: 13


In [27]:
# Cross product
import numpy as np

u = np.array([1, 2, 3])
v = np.array([-1, 1, 4])

# Compute the vector product of u and v
vector_product = np.cross(u, v)

print("Vector product of vectors u and v:", vector_product)

Vector product of vectors u and v: [ 5 -7  3]


# Transpose

In [1]:
# Transpose using the .T attribute
import numpy as np

# Define a column vector
v = np.array([[1],
              [2],
              [3]])

v_transpose = v.T

print("Original vector:")
print(v)
print("\nTranspose of the vector:")
print(v_transpose)

# v_transpose should be a row vector

Original vector:
[[1]
 [2]
 [3]]

Transpose of the vector:
[[1 2 3]]


In [2]:
# Transpose using numpy.transpose() function

import numpy as np

# Define a column vector
v = np.array([[1],
              [2],
              [3]])

v_transpose = np.transpose(v)

print("Original vector:")
print(v)
print("\nTranspose of the vector:")
print(v_transpose)

# v_transpose should be a row vector

Original vector:
[[1]
 [2]
 [3]]

Transpose of the vector:
[[1 2 3]]
